[tool.poetry]
name = "data-store"
version = "0.1.0"
description = "A simple data storage library"
authors = ["Your Name <email@gmail.com>"]
readme = "README.md"
packages = [
    { include = "data_store" }
]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.8.0"
utils = {git = "git@github.com:tex-corver/utils.git"}
icecream = "^2.1.3"
minio = "^7.2.7"
